### ISSUE TITLE
DraggableUI: Conflicts with Notepad mod

### ISSUE THREAD

**Issue by Tika96** [EtiamNullam/Etiam-ONI-Modpack#6]
* For testing purposes I have removed all other mods.

* The mod DraggableUI causes an exception on startup. It tries to access the file "State.json" which does not exist on the first start. ( See below )

* I have tried to create an empty file "State.json" since I don't know what keys / values are provided in a regular "State.json" file.

* Unfortunately this doesn't help to bypass  the startup fail. ( See below )

* Because I have only a very limited data volume per month, I am always playing offline. This causes some additional warnings in the output file. But it is not preventing me from playing: Without DraggableUI and with all other mods I am able to play ONI offline.
___

If you need additional information, please let me know.

Yours

Tika ( Tairon @ Steam )

[output_log - without State.JSON file.txt](https://github.com/EtiamNullam/Etiam-ONI-Modpack/files/4519315/output_log.-.without.State.JSON.file.txt)
___

[output_log - with empty State.JSON file.txt](https://github.com/EtiamNullam/Etiam-ONI-Modpack/files/4519316/output_log.-.with.empty.State.JSON.file.txt)

**Comment by EtiamNullam** [comment]
Thanks for submitting the issue!

This mod does not include `State.json` file. it is created the first time you move some UI around. So your `output_log` with error about missing `State.json` is actually fine.

I've tested and it works without internet connection for me.

On the other hand invalid `State.json` seems to throw exception and crash on startup (second log was helpful here) and I fixed that issue with the latest version (71cfbe2302592f8fa3c4216b3b94e46e4809f685).

I can't see a reason for the game to crash here other than this error (not really related to my mod though):
```
[22:24:43.377] [4] [WARNING] 23:40:13 KleiAccount: Exception getting Request Stream:Error: NameResolutionFailure
[22:24:43.377] [4] [WARNING] 23:40:13 KleiAccount: Exception (retrying in 32 seconds): Error: NameResolutionFailure
  at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <d2957de1c3fd4781a43d89572183136c>:0 
  at System.Net.HttpWebRequest.GetRequestStream () [0x0004e] in <d2957de1c3fd4781a43d89572183136c>:0 
  at ThreadedHttps`1[T].Send (System.Byte[] byteArray, System.Boolean isForce) [0x000c6] in <7ea7d27a47b94734a7a4a93fb41aec63>:0 
```

Above error didn't show up for me when I ran the game without internet connection.

Well you can try with this new version but I'm pretty sure it won't solve your main issue - only part where you ran the game with invalid `State.json` file. I think you should try new version and report back what happened (with new `output_log`).

**Comment by Tika96** [comment]
Many thanks for your very quick response !

I will try it out this evening ( Germany, GMT+1 ) and will report how well it works.

The "KleiAccount Exception" is only a warning. I guess the game tries to refresh the MOTD or something like this. Don't know exactly. But since I have it every time I am playing ONI that warning and it doesn't enforce the game to restart, I don't care about it :) In a long game session this warning message appears several times ( every 5 min ? ).

**Comment by Tika96** [comment]
Now, it works ... sort of ...

* I was able to start ONI with only DraggableUI active.
* The "State.JSON" was created within my test run.

* Enabling all other mods is still causing an error ( see below ). But I was now able to identify the cause.

* It's an conflict between your mod and the mod "Notepad".

* Disabling "DraggableUI" or "Notepad" will allow the game to start without any more serious errors ...

* ... which is pretty awesome if you consider the amount of mods I am using.
___

A single conflict among about 120 mods that what I would call a well done job ! :)
___

Do you want to contact the author of the "Notepad" mod ? Or do you want me to inform him about the conflict ?

Yours Tika

___

[output_log - conflict DraggableUI - Notepad.txt](https://github.com/EtiamNullam/Etiam-ONI-Modpack/files/4524914/output_log.-.conflict.DraggableUI.-.Notepad.txt)

**Comment by EtiamNullam** [comment]
Amazing!

Apparently when `Notepad` mod comes last it crashes without error but it points to error in my code when its the other way around. Your `output_log` made it very simple.

Now I fixed that error but sadly for some reason my mod has to come after `Notepad` in the mod order. I think its probably because `Notepad` adds some custom UI.

![image](https://user-images.githubusercontent.com/10875340/80161377-7f151000-85d0-11ea-86c7-66e8f622618b.png)

No need to contact author of "Notepad", I will do that.

Thanks for the help, let me know if it works for you.

**Comment by EtiamNullam** [comment]
Looks like I can't replicate the problem with mod order of `Notepad` and `DraggableUI` anymore.

Let me know if you can.

**Comment by Tika96** [comment]
Just checked it :

For me it's still the same error message. But I don't know, if the freaking Steam mod update system has delivered the most updated versions of the two mods in question for me.
___
Notepad.DLL 1.0.0.0 ... o.O
( Size 218.112 - crc32 28309b86 )
___
DraggableUI.DLL 2.2.0.0
( Size 8.704 - crc32 852fd59f )
___
Common.DLL
( Size 9.216 - crc32 430eb972 ) is

**Comment by Tika96** [comment]
Addendum :

It doesn't matter if DraggableUI is loaded first or Notepad is the first mod in the list. The error message is not changing.

**Comment by EtiamNullam** [comment]
@Tika96: newest version of `DraggableUI` is `2.2.2`
![image](https://user-images.githubusercontent.com/10875340/82130878-a1650c80-97cf-11ea-9370-67141590c70c.png)

I think Steam Workshop fails to download correct version like it often does. Try download this file directly from repository:
https://github.com/EtiamNullam/Etiam-ONI-Modpack/blob/master/Mods/DraggableUI/DraggableUI.dll

Sadly it can break on the next mod update.

**Comment by Tika96** [comment]
The newest versions are working fine !

DraggableUI.DLL 2.2.2.0
Common.DLL 3.2.1.0

I have run a few times into another problem ( thx to Steam ) : Steam / ONI have always been overwriting the manually installed libraries. I could have flushed the download cache, but this would have forced me to go online ... with the result that Steam would re-download all subscribed mods again with sometimes outdated versions.

Luckily Steam / ONI did not mind that I have write protected the libraries at last.

Klei should really established an independent mod distribution service. Steam sucks.
___
My most important problem has now been solved: With so many mods, the research report window has been to large to fit on the screen. I have not been able to close the report window without saving > quiting to main menu > reloading the game ;)
But did you know, that the "property window" ( don't know the in-game name of it ) of resources is not saved ? E.g. clicking on a resource in the list repeatedly restores the position.  I am able to move it. But cycling through a type of resources ( e.g. searching for a wild egg ) is a tedious task if the property window is always blocking the resource list again and again. But this is another story for another time ;)
